package com.notronix.mws.model;

public enum ReportType
{
    INVENTORY("_GET_FLAT_FILE_OPEN_LISTINGS_DATA_"),
    ALL_LISTINGS("_GET_MERCHANT_LISTINGS_ALL_DATA_"),
    ACTIVE_LISTINGS("_GET_MERCHANT_LISTINGS_DATA_"),
    INACTIVE_LISTINGS("_GET_MERCHANT_LISTINGS_INACTIVE_DATA_"),
    OPEN_LISTINGS("_GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT_"),
    OPEN_LISTINGS_LITE("_GET_MERCHANT_LISTINGS_DATA_LITE_"),
    OPEN_LISTINGS_LITER("_GET_MERCHANT_LISTINGS_DATA_LITER_"),
    CANCELLED_LISTINGS("_GET_MERCHANT_CANCELLED_LISTINGS_DATA_"),
    SOLD_LISTINGS("_GET_CONVERGED_FLAT_FILE_SOLD_LISTINGS_DATA_"),
    LISTING_QUALITY_AND_SUPPRESSED_LISTING("_GET_MERCHANT_LISTINGS_DEFECT_DATA_"),

//    FBA Inventory Reports
    FBA_FULFILLED_INVENTORY("_GET_AFN_INVENTORY_DATA_"),
    FBA_MULTI_COUNTRY_INVENTORY("_GET_AFN_INVENTORY_DATA_BY_COUNTRY_"),
    FBA_DAILY_INVENTORY_HISTORY("_GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA_"),
    FBA_MONTHLY_INVENTORY_HISTORY("_GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA_"),
    FBA_RECEIVED_INVENTORY("_GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA_"),
    FBA_RESERVED_INVENTORY("_GET_RESERVED_INVENTORY_DATA_"),
    FBA_INVENTORY_EVENT_DETAIL("_GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA_"),
    FBA_INVENTORY_ADJUSTMENTS("_GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA_"),
    FBA_INVENTORY_HEALTH("_GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA_"),
    FBA_MANAGE_INVENTORY("_GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA_"),
    FBA_MANAGE_INVENTORY_ARCHIVED("_GET_FBA_MYI_ALL_INVENTORY_DATA_"),
    FBA_CROSS_BORDER_INVENTORY_MOVEMENT("_GET_FBA_FULFILLMENT_CROSS_BORDER_INVENTORY_MOVEMENT_DATA_"),
    FBA_INBOUND_PERFORMANCE("_GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA_"),
    FBA_STRANDED_INVENTORY("_GET_STRANDED_INVENTORY_UI_DATA_"),
    FBA_BULK_FIX_STRANDED_INVENTORY("_GET_STRANDED_INVENTORY_LOADER_DATA_"),
    FBA_INVENTORY_AGE("_GET_FBA_INVENTORY_AGED_DATA_"),
    FBA_MANAGE_EXCESS_INVENTORY("_GET_EXCESS_INVENTORY_DATA_"),

//    FBA Payments Reports
    FBA_FEE_PREVIEW("_GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA_"),

//    Browse Tree Reports
        BROWSE_TREE_REPORT("_GET_XML_BROWSE_TREE_DATA_");

    private String value;

    ReportType(String value)
    {
        this.value = value;
    }

    public String value()
    {
        return value;
    }
}
