package com.notronix.mws.model;

public enum ReportType
{
    INVENTORY("_GET_FLAT_FILE_OPEN_LISTINGS_DATA_", false),
    ALL_LISTINGS("_GET_MERCHANT_LISTINGS_ALL_DATA_", false),
    ACTIVE_LISTINGS("_GET_MERCHANT_LISTINGS_DATA_", false),
    INACTIVE_LISTINGS("_GET_MERCHANT_LISTINGS_INACTIVE_DATA_", false),
    OPEN_LISTINGS("_GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT_", false),
    OPEN_LISTINGS_LITE("_GET_MERCHANT_LISTINGS_DATA_LITE_", false),
    OPEN_LISTINGS_LITER("_GET_MERCHANT_LISTINGS_DATA_LITER_", false),
    CANCELLED_LISTINGS("_GET_MERCHANT_CANCELLED_LISTINGS_DATA_", false),
    SOLD_LISTINGS("_GET_CONVERGED_FLAT_FILE_SOLD_LISTINGS_DATA_", false),
    LISTING_QUALITY_AND_SUPPRESSED_LISTING("_GET_MERCHANT_LISTINGS_DEFECT_DATA_", false),

//    FBA Inventory Reports
    FBA_FULFILLED_INVENTORY("_GET_AFN_INVENTORY_DATA_", true),
    FBA_MULTI_COUNTRY_INVENTORY("_GET_AFN_INVENTORY_DATA_BY_COUNTRY_", true),
    FBA_DAILY_INVENTORY_HISTORY("_GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA_", true),
    FBA_MONTHLY_INVENTORY_HISTORY("_GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA_", true),
    FBA_RECEIVED_INVENTORY("_GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA_", true),
    FBA_RESERVED_INVENTORY("_GET_RESERVED_INVENTORY_DATA_", true),
    FBA_INVENTORY_EVENT_DETAIL("_GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA_", true),
    FBA_INVENTORY_ADJUSTMENTS("_GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA_", true),
    FBA_INVENTORY_HEALTH("_GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA_", true),
    FBA_MANAGE_INVENTORY("_GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA_", true),
    FBA_MANAGE_INVENTORY_ARCHIVED("_GET_FBA_MYI_ALL_INVENTORY_DATA_", true),
    FBA_CROSS_BORDER_INVENTORY_MOVEMENT("_GET_FBA_FULFILLMENT_CROSS_BORDER_INVENTORY_MOVEMENT_DATA_", true),
    FBA_INBOUND_PERFORMANCE("_GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA_", true),
    FBA_STRANDED_INVENTORY("_GET_STRANDED_INVENTORY_UI_DATA_", true),
    FBA_BULK_FIX_STRANDED_INVENTORY("_GET_STRANDED_INVENTORY_LOADER_DATA_", true),
    FBA_INVENTORY_AGE("_GET_FBA_INVENTORY_AGED_DATA_", false),
    FBA_MANAGE_EXCESS_INVENTORY("_GET_EXCESS_INVENTORY_DATA_", true),
    FBA_STORAGE_FEES("_GET_FBA_STORAGE_FEE_CHARGES_DATA_", true),

//    FBA Payments Reports
    FBA_FEE_PREVIEW("_GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA_", true),

//    Browse Tree Reports
        BROWSE_TREE_REPORT("_GET_XML_BROWSE_TREE_DATA_", true);

    private String value;
    private boolean supportsMultipleMarketplaces;

    ReportType(String value, boolean supportsMultipleMarketplaces)
    {
        this.value = value;
        this.supportsMultipleMarketplaces = supportsMultipleMarketplaces;
    }

    public String value()
    {
        return value;
    }

    public boolean supportsMultipleMarketplaces() {
        return supportsMultipleMarketplaces;
    }
}
