package com.notronix.mws.api.model;

public enum FeedType
{
    PRODUCT("_POST_PRODUCT_DATA_"),
    INVENTORY("_POST_INVENTORY_AVAILABILITY_DATA_"),
    OVERRIDES("_POST_PRODUCT_OVERRIDES_DATA_"),
    PRICING("_POST_PRODUCT_PRICING_DATA_"),
    PRODUCT_IMAGES("_POST_PRODUCT_IMAGE_DATA_"),
    RELATIONSHIPS("_POST_PRODUCT_RELATIONSHIP_DATA_"),
    FLAT_FILE_INVENTORY_LOADER("_POST_FLAT_FILE_INVLOADER_DATA_"),
    FLAT_FILE_LISTINGS("_POST_FLAT_FILE_LISTINGS_DATA_"),
    FLAT_FILE_BOOK_LOADER("_POST_FLAT_FILE_BOOKLOADER_DATA_"),
    FLAT_FILE_MUSIC_LOADER("_POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA_"),
    FLAT_FILE_VIDEO_LOADER("_POST_FLAT_FILE_LISTINGS_DATA_"),
    FLAT_FILE_PRICE_AND_QUANTITY_UPDATE("_POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_"),
    UIEE_INVENTORY("_POST_UIEE_BOOKLOADER_DATA_"),
    ACES_3_0_DATA("_POST_STD_ACES_DATA_"),
    ORDER_ACKNOWLEDGEMENT("_POST_ORDER_ACKNOWLEDGEMENT_DATA_"),
    ORDER_ADJUSTMENT("_POST_PAYMENT_ADJUSTMENT_DATA_"),
    ORDER_FULFILLMENT("_POST_ORDER_FULFILLMENT_DATA_"),
    INVOICE_CONFIRMATION("_POST_INVOICE_CONFIRMATION_DATA_"),
    FLAT_FILE_ORDER_ACKNOWLEDGEMENT("_POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA_"),
    FLAT_FILE_ORDER_ADJUSTMENT("_POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA_"),
    FLAT_FILE_ORDER_FULFILLMENT("_POST_FLAT_FILE_FULFILLMENT_DATA_"),
    FLAT_FILE_INVOICE_CONFIRMATION("_POST_FLAT_FILE_INVOICE_CONFIRMATION_DATA_");

    private String value;

    FeedType(String value)
    {
        this.value = value;
    }

    public String value()
    {
        return this.value;
    }
}
